---
language: rust
dist: trusty
sudo: false

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
    - libssl-dev
    - protobuf-compiler

matrix:
  include:
  - rust: nightly
    before_deploy: cargo doc --no-deps

install:
  - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  - curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
  - unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* $HOME/.cargo/bin/

before_script:
  - cd orca
  - cargo clean

script:
  - rustdoc --test ../README.md -L target/debug -L target/debug/deps
  - cargo test

after_success:
  - bash <(curl -Ls https://codecov.io/bash)
  - curl -X POST -H "Content-Type: application/json" -d '{"content":"Orca build was successful."}' $DISCORD_WEBHOOK

after_failure:
  - curl -X POST -H "Content-Type: application/json" -d '{"content":"Orca build has failed."}' $DISCORD_WEBHOOK

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: gh-pages
  local_dir: target/doc
  on:
    branch: master
    repo: crypto-bank/orca
    rust: nightly

notifications:
  email:
    on_success: never
