[package]
name = "orca_markets"
version = "0.1.0"
authors = ["crackcomm <crackcomm@gmail.com>"]

[dependencies]
orca_currency = { path = "../currency" }

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

ordered-float = "*"
