(function() {var implementors = {};
implementors["orca"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"orca/core/currency/struct.CurrencyPair.html\" title=\"struct orca::core::currency::CurrencyPair\">CurrencyPair</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"orca/core/currency/struct.CurrencyVolume.html\" title=\"struct orca::core::currency::CurrencyVolume\">CurrencyVolume</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"orca/core/currency/enum.Currency.html\" title=\"enum orca::core::currency::Currency\">Currency</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"orca/core/market/enum.Market.html\" title=\"enum orca::core::market::Market\">Market</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"orca/core/order/struct.Order.html\" title=\"struct orca::core::order::Order\">Order</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"orca/core/order/struct.RawOrder.html\" title=\"struct orca::core::order::RawOrder\">RawOrder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"orca/core/order/enum.OrderKind.html\" title=\"enum orca::core::order::OrderKind\">OrderKind</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"orca/core/trade/struct.Trade.html\" title=\"struct orca::core::trade::Trade\">Trade</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"orca/core/trade/struct.RawTrade.html\" title=\"struct orca::core::trade::RawTrade\">RawTrade</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
