
//
// WARNING - this file is autogenerated from `symbol.rs.tmpl` - WARNING
//

use std::str::FromStr;

/// Symbol of a currency or crypto currency
#[derive(Serialize, Deserialize, Eq, PartialEq, Debug, Copy, Clone, Hash)]
pub enum Symbol {
    /// Euro
    EUR,
    /// United States Dollar
    USD,
    /// Abncoin
    ABN,
    /// ArtByte
    ABY,
    /// AsiaCoin
    AC,
    /// NxttyACCI
    ACCI,
    /// Aces
    ACES,
    /// Avoncoin
    ACN,
    /// Acoin
    ACOIN,
    /// AnarchistsPrime
    ACP,
    /// AudioCoin
    ADC,
    /// Asiadigicoin
    ADCN,
    /// The Aladin
    ADT,
    /// Adzcoin
    ADZ,
    /// Aeon
    AEON,
    /// AgrolifeCoin
    AGLC,
    /// Agoras Tokens
    AGRS,
    /// Advanced Internet Blocks
    AIB,
    /// AIRcoin
    AIR,
    /// Allion
    ALL,
    /// Antilitecoin
    ALTC,
    /// AmberCoin
    AMBER,
    /// AMIS
    AMIS,
    /// Synereo
    AMP,
    /// AmsterdamCoin
    AMS,
    /// Anoncoin
    ANC,
    /// AntShares
    ANS,
    /// AntiBitcoin
    ANTI,
    /// AlpaCoin
    APC,
    /// ARbit
    ARB,
    /// AquariusCoin
    ARCO,
    /// Ardor
    ARDR,
    /// Argentum
    ARG,
    /// Argus
    ARGUS,
    /// Aricoin
    ARI,
    /// Ark
    ARK,
    /// AllSafe
    ASAFE,
    /// AsicCoin
    ASC,
    /// Atmos
    ATMS,
    /// Atomic Coin
    ATOM,
    /// Artex Coin
    ATX,
    /// AurumCoin
    AU,
    /// Alexium
    AUM,
    /// Auroracoin
    AUR,
    /// AvatarCoin
    AV,
    /// AxFunds
    AXF,
    /// B3Coin
    B3,
    /// BitAlphaCoin
    BAC,
    /// LuckChain
    BASH,
    /// BitBay
    BAY,
    /// BitConnect
    BCC,
    /// BitcoinFast
    BCF,
    /// Bytecoin
    BCN,
    /// Bitcrystals
    BCY,
    /// BelaCoin
    BELA,
    /// BenjiRolls
    BENJI,
    /// BERNcash
    BERN,
    /// BestChain
    BEST,
    /// BagCoin
    BGC,
    /// Bikercoin
    BIC,
    /// BigUp
    BIGUP,
    /// BioBar
    BIOB,
    /// BiosCrypto
    BIOS,
    /// BipCoin
    BIP,
    /// First Bitcoin
    BIT,
    /// BitBean
    BITB,
    /// bitBTC
    BITBTC,
    /// bitCNY
    BITCNY,
    /// bitEUR
    BITEUR,
    /// bitGold
    BITGOLD,
    /// Bitstar
    BITS,
    /// bitSilver
    BITSILVER,
    /// bitUSD
    BITUSD,
    /// Bitz
    BITZ,
    /// BlazerCoin
    BLAZR,
    /// Blakecoin
    BLC,
    /// Blitzcash
    BLITZ,
    /// BlackCoin
    BLK,
    /// Blocknet
    BLOCK,
    /// BlockPay
    BLOCKPAY,
    /// BillaryCoin
    BLRY,
    /// BlueCoin
    BLU,
    /// BlazeCoin
    BLZ,
    /// Doubloon
    BOAT,
    /// Dobbscoin
    BOB,
    /// Bolivarcoin
    BOLI,
    /// Bond
    BOND,
    /// BoostCoin
    BOST,
    /// Bitpark Coin
    BPC,
    /// Braincoin
    BRAIN,
    /// BritCoin
    BRIT,
    /// Breakout
    BRK,
    /// Breakout Stake
    BRX,
    /// BowsCoin
    BSC,
    /// BitSend
    BSD,
    /// Blackstar
    BSTAR,
    /// GlobalBoost-Y
    BSTY,
    /// Bata
    BTA,
    /// BitBar
    BTB,
    /// Bitcoin
    BTC,
    /// BitcoinDark
    BTCD,
    /// Bitcurrency
    BTCR,
    /// Bitcoin Scrypt
    BTCS,
    /// Bitcloud
    BTD,
    /// Bitgem
    BTG,
    /// Bitmark
    BTM,
    /// BitQuark
    BTQ,
    /// BitShares
    BTS,
    /// BTSR
    BTSR,
    /// Bitcoin Unlimited (Futures)
    BTU,
    /// SwagBucks
    BUCKS,
    /// CryptoBuck
    BUK,
    /// BumbaCoin
    BUMBA,
    /// BunnyCoin
    BUN,
    /// President Sanders
    BURN,
    /// Burst
    BURST,
    /// BeaverCoin
    BVC,
    /// Bitcedi
    BXC,
    /// BitTokens
    BXT,
    /// Bytecent
    BYC,
    /// Coin2.1
    C2,
    /// Cabbage
    CAB,
    /// Bitland
    CADASTRAL,
    /// CageCoin
    CAGE,
    /// CaliphCoin
    CALC,
    /// CannabisCoin
    CANN,
    /// Bottlecaps
    CAP,
    /// Carboncoin
    CARBON,
    /// Cashcoin
    CASH,
    /// Casino
    CASINO,
    /// CBD Crystals
    CBD,
    /// Crypto Bullion
    CBX,
    /// CyberCoin
    CC,
    /// CCMiner
    CCM100,
    /// Cannacoin
    CCN,
    /// CryptoCarbon
    CCRB,
    /// Canada eCoin
    CDN,
    /// CryptoEscudo
    CESC,
    /// Californium
    CF,
    /// 23 Skidoo
    CHAO,
    /// ChainCoin
    CHC,
    /// ChessCoin
    CHESS,
    /// ChoofCoin
    CHOOF,
    /// Cryptojacks
    CJ,
    /// Clams
    CLAM,
    /// Clinton
    CLINT,
    /// CloakCoin
    CLOAK,
    /// ClubCoin
    CLUB,
    /// Cashme
    CME,
    /// Comet
    CMT,
    /// CHNCoin
    CNC,
    /// Coin(O)
    CNO,
    /// Centurion
    CNT,
    /// PayCon
    CON,
    /// Concoin
    CONX,
    /// CorgiCoin
    CORG,
    /// Circuits of Value
    COVAL,
    /// CoExistCoin
    COXST,
    /// Capricoin
    CPC,
    /// Creditbit
    CRBIT,
    /// CrevaCoin
    CREVA,
    /// CRTCoin
    CRT,
    /// Crown
    CRW,
    /// Chronos
    CRX,
    /// CasinoCoin
    CSC,
    /// Cashout
    CSH,
    /// Crypto
    CTO,
    /// DigiCube
    CUBE,
    /// CureCoin
    CURE,
    /// Colossuscoin V2
    CV2,
    /// CryptoWorldX Token
    CWXT,
    /// Coinonat
    CXT,
    /// Cycling Coin
    CYC,
    /// Cypher
    CYP,
    /// Darcrus
    DAR,
    /// Dash
    DASH,
    /// Digital Bullion Gold
    DBG,
    /// DubaiCoin
    DBIC,
    /// DubaiCoin
    DBIX,
    /// Debitcoin
    DBTC,
    /// Decred
    DCR,
    /// DeltaCredits
    DCRE,
    /// Decent (Pre-Launch)
    DCT,
    /// Deutsche eMark
    DEM,
    /// Destiny
    DES,
    /// DeusCoin
    DEUS,
    /// InstantDEX
    DEX,
    /// DigiByte
    DGB,
    /// Digitalcoin
    DGC,
    /// Digital Credits
    DGCS,
    /// DigixDAO
    DGD,
    /// DIBCOIN
    DIBC,
    /// Dimecoin
    DIME,
    /// DarkLisk
    DISK,
    /// Dix Asset
    DIX,
    /// Dollarcoin
    DLC,
    /// DAPPSTER
    DLISK,
    /// DynamicCoin
    DMC,
    /// Diamond
    DMD,
    /// Dogecoin
    DOGE,
    /// Dollar Online
    DOLLAR,
    /// DopeCoin
    DOPE,
    /// Dotcoin
    DOT,
    /// DigitalPrice
    DP,
    /// DPAY
    DPAY,
    /// DT Token
    DRACO,
    /// BTCDragon
    DRAGON,
    /// Dreamcoin
    DRM,
    /// Digital Rupees
    DRS,
    /// Dashcoin
    DSH,
    /// Databits
    DTB,
    /// Digitalfund
    DTF,
    /// Dubstep
    DUB,
    /// ParallelCoin
    DUO,
    /// Devcoin
    DVC,
    /// DeepWebCash
    DWC,
    /// Dynamic
    DYN,
    /// EarthCoin
    EAC,
    /// EB3 Coin
    EB3,
    /// Ebittree Coin
    EBT,
    /// E-Currency Coin 
    ECC,
    /// E-coin
    ECN,
    /// Edgeless
    EDG,
    /// E-Dinar Coin
    EDR,
    /// EDRCoin
    EDRC,
    /// e-Gulden
    EFL,
    /// EvergreenCoin
    EGC,
    /// EggCoin
    EGG,
    /// EGO
    EGO,
    /// Elcoin
    EL,
    /// Elacoin
    ELC,
    /// Elementrem
    ELE,
    /// Elysium
    ELS,
    /// Emercoin
    EMC,
    /// Einsteinium
    EMC2,
    /// Emerald Crypto
    EMD,
    /// Ethereum Movie Venture
    EMV,
    /// Energycoin
    ENRG,
    /// Eternity
    ENT,
    /// EuropeCoin
    ERC,
    /// Eryllium
    ERY,
    /// Espers
    ESP,
    /// Ethereum Classic
    ETC,
    /// Ethereum
    ETH,
    /// Eurocoin
    EUC,
    /// Evil Coin
    EVIL,
    /// Evotion
    EVO,
    /// ExclusiveCoin
    EXCL,
    /// Expanse
    EXP,
    /// FairCoin
    FAIR,
    /// Fazzcoin
    FAZZ,
    /// FuelCoin
    FC2,
    /// Fantomcoin
    FCN,
    /// Factom
    FCT,
    /// Future Digital Currency
    FDC,
    /// FedoraShare
    FEDS,
    /// FireFlyCoin
    FFC,
    /// Firecoin
    FIRE,
    /// FujiCoin
    FJC,
    /// Flaxscript
    FLAX,
    /// FoldingCoin
    FLDC,
    /// FlorinCoin
    FLO,
    /// FlutterCoin
    FLT,
    /// FlavorCoin
    FLVR,
    /// Flycoin
    FLY,
    /// Freicoin
    FRC,
    /// Fargocoin
    FRGC,
    /// Franko
    FRK,
    /// Francs
    FRN,
    /// FirstCoin
    FRST,
    /// FrankyWillCoin
    FRWC,
    /// Fastcoin
    FST,
    /// Feathercoin
    FTC,
    /// Alphabet Coin Fund
    FUN,
    /// Cryptofund
    FUND,
    /// The Cypherfunks
    FUNK,
    /// FuzzBalls
    FUZZ,
    /// G3N
    G3N,
    /// GAIA
    GAIA,
    /// UGAIN
    GAIN,
    /// Gambit
    GAM,
    /// GameCredits
    GAME,
    /// Gapcoin
    GAP,
    /// President Johnson
    GARY,
    /// GAYcoin
    GAY,
    /// GoldBlocks
    GB,
    /// GBCGoldCoin
    GBC,
    /// Golos Gold
    GBG,
    /// Global Business Revolution
    GBRC,
    /// GameBet Coin
    GBT,
    /// Byteball
    GBYTE,
    /// GCoin
    GCN,
    /// Global Currency Reserve
    GCR,
    /// GeertCoin
    GEERT,
    /// GetGems
    GEMZ,
    /// GeoCoin
    GEO,
    /// GlobalCoin
    GLC,
    /// GoldCoin
    GLD,
    /// Gambleo
    GMB,
    /// GameLeagueCoin
    GML,
    /// GoldMaxCoin
    GMX,
    /// Golem
    GNT,
    /// Golos
    GOLOS,
    /// GoldPieces
    GP,
    /// GPU Coin
    GPU,
    /// GridCoin
    GRC,
    /// Greencoin
    GREV2,
    /// Granite
    GRN,
    /// Groestlcoin
    GRS,
    /// Grantcoin
    GRT,
    /// Guarany
    GUA,
    /// Guncoin
    GUN,
    /// Guppy (Pre-Launch)
    GUP,
    /// HamRadioCoin
    HAM,
    /// HoboNickels
    HBN,
    /// Happy Creator Coin
    HCC,
    /// HEAT
    HEAT,
    /// President Clinton
    HILL,
    /// Hirocoin
    HIRO,
    /// Hacker Gold
    HKG,
    /// Lepaoquan
    HLB,
    /// Hommalicoin
    HMC,
    /// HempCoin
    HMP,
    /// Helleniccoin
    HNC,
    /// HOdlcoin
    HODL,
    /// Honey
    HONEY,
    /// Happycoin
    HPC,
    /// HitCoin
    HTC,
    /// HTMLCOIN
    HTML5,
    /// HunterCoin
    HUC,
    /// High Voltage
    HVCO,
    /// Hexx
    HXX,
    /// HyperStake
    HYP,
    /// Horizon
    HZ,
    /// I0Coin
    I0C,
    /// iBank
    IBANK,
    /// iCash
    ICASH,
    /// Iconomi
    ICN,
    /// ICOBID
    ICOB,
    /// Iconic
    ICON,
    /// ICO OpenLedger
    ICOO,
    /// Infinitecoin
    IFC,
    /// InflationCoin
    IFLT,
    /// Impeachcoin
    IMPCH,
    /// ImpulseCoin
    IMPS,
    /// Independent Money System
    IMS,
    /// Impact
    IMX,
    /// Incent
    INCNT,
    /// Influxcoin
    INFX,
    /// Inpay
    INPAY,
    /// InsaneCoin
    INSANE,
    /// I/O Coin
    IOC,
    /// ION
    ION,
    /// Internet of People
    IOP,
    /// IslaCoin
    ISL,
    /// InvisibleCoin
    IVZ,
    /// Ixcoin
    IXC,
    /// Joincoin
    J,
    /// Jin Coin
    JIN,
    /// Jinn
    JINN,
    /// JIO Token
    JIO,
    /// Janus
    JNS,
    /// JobsCoin
    JOBS,
    /// Jewels
    JWL,
    /// KashhCoin
    KASHH,
    /// Darsek
    KED,
    /// KiloCoin
    KLC,
    /// Komodo
    KMD,
    /// Kobocoin
    KOBO,
    /// KoreCoin
    KORE,
    /// Karbowanec
    KRB,
    /// KarmaToken
    KTN,
    /// Kurrent
    KURT,
    /// KushCoin
    KUSH,
    /// LanaCoin
    LANA,
    /// Lazaruscoin
    LAZ,
    /// LBRY Credits
    LBC,
    /// LandCoin
    LDCN,
    /// LiteDoge
    LDOGE,
    /// LeaCoin
    LEA,
    /// LeCoin
    LEC,
    /// LEOcoin
    LEO,
    /// LePen
    LEPEN,
    /// Lex4All
    LEX,
    /// BigLifeCoin
    LFC,
    /// LetItRide
    LIR,
    /// LinkedCoin
    LKC,
    /// Lykke
    LKK,
    /// LoMoCoin
    LMC,
    /// Woodcoin
    LOG,
    /// LottoCoin
    LOT,
    /// Lisk
    LSK,
    /// LiteBar
    LTB,
    /// LTBcoin
    LTBC,
    /// Litecoin
    LTC,
    /// Litecred
    LTCR,
    /// LAthaan
    LTH,
    /// Luna Coin
    LUNA,
    /// LevoPlus
    LVPS,
    /// Machinecoin
    MAC,
    /// SatoshiMadness
    MAD,
    /// MaidSafeCoin
    MAID,
    /// Marijuanacoin
    MAR,
    /// MarxCoin
    MARX,
    /// Mavro
    MAVRO,
    /// MaxCoin
    MAX,
    /// Mbitbooks
    MBIT,
    /// MobileCash
    MBL,
    /// Megacoin
    MEC,
    /// MediterraneanCoin
    MED,
    /// Pepe
    MEME,
    /// Kittehcoin
    MEOW,
    /// Mercury
    MER,
    /// MetalCoin
    METAL,
    /// Mind Gene
    MG,
    /// Magnum
    MGM,
    /// Xiaomicoin
    MI,
    /// MiloCoin
    MILO,
    /// Mintcoin
    MINT,
    /// Melon
    MLN,
    /// MMXVI
    MMXVI,
    /// MindCoin
    MND,
    /// Mineum
    MNM,
    /// Moin
    MOIN,
    /// MojoCoin
    MOJO,
    /// MonaCoin
    MONA,
    /// Moneta
    MONETA,
    /// MoneyCoin
    MONEY,
    /// Mooncoin
    MOON,
    /// Motocoin
    MOTO,
    /// Master Swiscoin
    MSCN,
    /// MustangCoin
    MST,
    /// Metal Music Coin
    MTLMC3,
    /// MTMGaming
    MTM,
    /// MonetaryUnit
    MUE,
    /// MikeTheMug
    MUG,
    /// MUSE
    MUSE,
    /// Musicoin
    MUSIC,
    /// MarteXcoin
    MXT,
    /// MazaCoin
    MZC,
    /// NautilusCoin
    NAUT,
    /// NAV Coin
    NAV,
    /// BitCentavo
    NBE,
    /// netBit
    NBIT,
    /// NeosCoin
    NEOS,
    /// NetCoin
    NET,
    /// Netko
    NETKO,
    /// NeuCoin
    NEU,
    /// NevaCoin
    NEVA,
    /// Newbium
    NEWB,
    /// IncaKoin
    NKA,
    /// NoLimitCoin
    NLC2,
    /// Gulden
    NLG,
    /// Namecoin
    NMC,
    /// NobleCoin
    NOBL,
    /// NodeCoin
    NODC,
    /// DNotes
    NOTE,
    /// NuShares
    NSR,
    /// Neptune Classic
    NTCC,
    /// Neutron
    NTRN,
    /// Novacoin
    NVC,
    /// Nexium
    NXC,
    /// Nexus
    NXS,
    /// Nxt
    NXT,
    /// Nyancoin
    NYAN,
    /// NewYorkCoin
    NYC,
    /// OBITS
    OBITS,
    /// BurstOcean
    OCEAN,
    /// OCOW
    OCOW,
    /// OKCash
    OK,
    /// Omicron
    OMC,
    /// Omni
    OMNI,
    /// Operand
    OP,
    /// Opal
    OPAL,
    /// Opescoin
    OPES,
    /// Orbitcoin
    ORB,
    /// Orlycoin
    ORLY,
    /// OsmiumCoin
    OS76,
    /// P7Coin
    P7C,
    /// Paccoin
    PAC,
    /// Pakcoin
    PAK,
    /// Pangea Poker
    PANGEA,
    /// Pascal Coin
    PASC,
    /// Pascal Lite
    PASL,
    /// PayPeer
    PAYP,
    /// PabyosiCoin
    PBC,
    /// Pabyosi Coin (Special)
    PCS,
    /// Project Decorum
    PDC,
    /// PinkDog
    PDG,
    /// Pepe Cash
    PEPECASH,
    /// PosEx
    PEX,
    /// Photon
    PHO,
    /// Philosopher Stones
    PHS,
    /// PIECoin
    PIE,
    /// Piggycoin
    PIGGY,
    /// PinkCoin
    PINK,
    /// Pioneershares
    PIO,
    /// PipCoin
    PIP,
    /// PIVX
    PIVX,
    /// PizzaCoin
    PIZZA,
    /// ParkByte
    PKB,
    /// PLNcoin
    PLNC,
    /// Pluton
    PLU,
    /// Pandacoin
    PND,
    /// PokeCoin
    POKE,
    /// PonziCoin
    PONZI,
    /// PopularCoin
    POP,
    /// PostCoin
    POST,
    /// PoSW Coin
    POSW,
    /// PotCoin
    POT,
    /// Peercoin
    PPC,
    /// Prototanium
    PR,
    /// PRCoin
    PRC,
    /// President Trump
    PRES,
    /// PrismChain
    PRM,
    /// Printerium
    PRX,
    /// Pesobit
    PSB,
    /// Psilocybin
    PSY,
    /// Pesetacoin
    PTC,
    /// Pulse
    PULSE,
    /// PutinCoin
    PUT,
    /// Powercoin
    PWR,
    /// PX
    PX,
    /// Phoenixcoin
    PXC,
    /// Prime-XI
    PXI,
    /// Quebecoin
    QBC,
    /// Qibuck
    QBK,
    /// Cubits
    QBT,
    /// QuazarCoin
    QCN,
    /// Qora
    QORA,
    /// Quark
    QRK,
    /// Quatloo
    QTL,
    /// Qwark
    QWARK,
    /// Radium
    RADS,
    /// Rare Pepe Party
    RAREPEPEPRTY,
    /// Rubies
    RBIES,
    /// Rimbit
    RBT,
    /// Ripto Bux
    RBX,
    /// Rubycoin
    RBY,
    /// RussiaCoin
    RC,
    /// Rcoin
    RCN,
    /// ReddCoin
    RDD,
    /// RedCoin
    RED,
    /// ReeCoin
    REE,
    /// Augur
    REP,
    /// Revenu
    REV,
    /// RHFCoin
    RHFC,
    /// Riecoin
    RIC,
    /// RichCoin
    RICHX,
    /// Ride My Car
    RIDE,
    /// Rise
    RISE,
    /// RLC
    RLC,
    /// Renos
    RNS,
    /// Round
    ROUND,
    /// RoyalCoin
    ROYAL,
    /// RonPaulCoin
    RPC,
    /// RubleBit
    RUBIT,
    /// RoyalCoin 2
    RYCN,
    /// Safe Exchange Coin
    SAFEX,
    /// Sharkcoin
    SAK,
    /// Save and Gain
    SANDG,
    /// SATOSHICARD
    SATOSHICARD,
    /// Steem Dollars
    SBD,
    /// Siacoin
    SC,
    /// Scorecoin
    SCORE,
    /// Scotcoin
    SCOT,
    /// SecretCoin
    SCRT,
    /// ShadowCash
    SDC,
    /// SydPak
    SDP,
    /// Sequence
    SEQ,
    /// Solarflarecoin
    SFC,
    /// Shilling
    SH,
    /// ShellPay
    SHELL,
    /// Shift
    SHIFT,
    /// Shorty
    SHORTY,
    /// SIBCoin
    SIB,
    /// Storjcoin X
    SJCX,
    /// Skeincoin
    SKC,
    /// Sakuracoin
    SKR,
    /// Skycoin
    SKY,
    /// Selfiecoin
    SLFI,
    /// Sterlingcoin
    SLG,
    /// Sling
    SLING,
    /// SolarCoin
    SLR,
    /// SaluS
    SLS,
    /// SmartCoin
    SMC,
    /// SmileyCoin
    SMLY,
    /// SingularDTV
    SNGLS,
    /// Synergy
    SNRG,
    /// Soarcoin
    SOAR,
    /// SongCoin
    SONG,
    /// SoonCoin
    SOON,
    /// SoulCoin
    SOUL,
    /// SpaceCoin
    SPACE,
    /// SproutsExtreme
    SPEX,
    /// Sphere
    SPHR,
    /// SportsCoin
    SPORT,
    /// SpreadCoin
    SPR,
    /// Sprouts
    SPRTS,
    /// Spots
    SPT,
    /// SecureCoin
    SRC,
    /// Startcoin
    START,
    /// Steem
    STEEM,
    /// Steps
    STEPS,
    /// Stratis
    STRAT,
    /// SuperTurboStake
    STRB,
    /// Stress
    STS,
    /// Sativacoin
    STV,
    /// Bitswift
    SWIFT,
    /// Swing
    SWING,
    /// Swarm City
    SWT,
    /// Sexcoin
    SXC,
    /// Syndicate
    SYNX,
    /// SysCoin
    SYS,
    /// TaaS (Pre-Launch)
    TAAS,
    /// TagCoin
    TAG,
    /// TAGRcoin
    TAGR,
    /// TajCoin
    TAJ,
    /// BTCtalkcoin
    TALK,
    /// Tattoocoin
    TATO,
    /// T-coin
    TCOIN,
    /// TheCreed
    TCR,
    /// TeamUp
    TEAM,
    /// TEKcoin
    TEK,
    /// Tellurion
    TELL,
    /// TeraCoin
    TERA,
    /// TeslaCoin
    TES,
    /// TeslaCoilCoin
    TESLA,
    /// Tigercoin
    TGC,
    /// HempCoin
    THC,
    /// TechShares
    THS,
    /// True Investment Coin
    TIC,
    /// Chronobank
    TIME,
    /// FedoraCoin
    TIPS,
    /// Titcoin
    TIT,
    /// Tickets
    TIX,
    /// Tokes
    TKS,
    /// TodayCoin
    TODAY,
    /// SwapToken
    TOKEN,
    /// Torcoin
    TOR,
    /// KolschCoin
    TP1,
    /// Terracoin
    TRC,
    /// Triangles
    TRI,
    /// TrickyCoin
    TRICK,
    /// Triggers
    TRIG,
    /// Truckcoin
    TRK,
    /// Trollcoin
    TROLL,
    /// TROPTIONS
    TROPTIONS,
    /// WeTrust
    TRST,
    /// TrumpCoin
    TRUMP,
    /// TrustPlus
    TRUST,
    /// Tristar Coin
    TSTR,
    /// TittieCoin
    TTC,
    /// TransferCoin
    TX,
    /// UCoin
    U,
    /// Ubiq
    UBQ,
    /// UFO Coin
    UFO,
    /// Unitus
    UIS,
    /// UnbreakableCoin
    UNB,
    /// UNCoin
    UNC,
    /// Universe
    UNI,
    /// UniBURST
    UNIBURST,
    /// UniCoin
    UNIC,
    /// Universal Currency
    UNIT,
    /// GameUnits
    UNITS,
    /// SuperNET
    UNITY,
    /// Unobtanium
    UNO,
    /// UR
    UR,
    /// Unrealcoin
    URC,
    /// Uro
    URO,
    /// Ultimate Secure Cash
    USC,
    /// Tether
    USDT,
    /// NuBits
    USNBT,
    /// UtaCoin
    UTA,
    /// UltraCoin
    UTC,
    /// Valorbit
    VAL,
    /// VPNCoin
    VASH,
    /// VirtualCoin
    VC,
    /// Vector
    VEC2,
    /// VegasCoin
    VGC,
    /// Viacoin
    VIA,
    /// PureVidz
    VIDZ,
    /// VIP Tokens
    VIP,
    /// Visio
    VISIO,
    /// Veltor
    VLT,
    /// Vault Coin
    VLTC,
    /// Voxels
    VOX,
    /// VapersCoin
    VPRC,
    /// VeriCoin
    VRC,
    /// VeriumReserve
    VRM,
    /// Veros
    VRS,
    /// vSlice
    VSL,
    /// Virtacoin
    VTA,
    /// Vertcoin
    VTC,
    /// vTorrent
    VTR,
    /// Victoriouscoin
    VTY,
    /// WA Space
    WA,
    /// WARP
    WARP,
    /// Waves
    WAVES,
    /// WayGuide
    WAY,
    /// Wild Beast Block
    WBB,
    /// Waves Community Token
    WCT,
    /// WorldCoin
    WDC,
    /// Wowecoin
    WEC,
    /// Wexcoin
    WEX,
    /// World Gold Coin
    WGC,
    /// Wings (Pre-Launch)
    WINGS,
    /// WMCoin
    WMC,
    /// HealthyWormCoin
    WORM,
    /// Wowcoin
    WOW,
    /// WeAreSatoshi
    WSX,
    /// Wyvern
    WYV,
    /// X2
    X2,
    /// Asch
    XAS,
    /// Xaucoin
    XAU,
    /// Xaurum
    XAUR,
    /// Boolberry
    XBB,
    /// Bitcoin Plus
    XBC,
    /// Bitcoin 21
    XBTC21,
    /// Beatcoin
    XBTS,
    /// XtraBYtes
    XBY,
    /// Cannabis Industry Coin
    XCI,
    /// Cryptonite
    XCN,
    /// X-Coin
    XCO,
    /// Counterparty
    XCP,
    /// Creatio
    XCRE,
    /// C-Bit
    XCT,
    /// XDE II
    XDE2,
    /// DigitalNote
    XDN,
    /// NEM
    XEM,
    /// Xenixcoin
    XEN,
    /// Forevercoin
    XFC,
    /// GoldReserve
    XGR,
    /// HiCoin
    XHI,
    /// International Diamond
    XID,
    /// Joulecoin
    XJO,
    /// Stellar Lumens
    XLM,
    /// Solaris
    XLR,
    /// Magi
    XMG,
    /// Monero
    XMR,
    /// Myriad
    XMY,
    /// Enigma
    XNG,
    /// Xonecoin
    XOC,
    /// Internet of Things
    XOT,
    /// XP
    XP,
    /// PetroDollar
    XPD,
    /// Primecoin
    XPM,
    /// PlatinumBAR
    XPTX,
    /// PayCoin
    XPY,
    /// Quotient
    XQN,
    /// Ratecoin
    XRA,
    /// RaiBlocks
    XRB,
    /// Rawcoin
    XRC,
    /// RevolverCoin
    XRE,
    /// Ripple
    XRP,
    /// Spectrecoin
    XSPEC,
    /// Stealthcoin
    XST,
    /// Safe Trade Coin
    XSTC,
    /// TileCoin
    XTC,
    /// Tao
    XTO,
    /// Vcash
    XVC,
    /// The Vegan Initiative
    XVE,
    /// Verge
    XVG,
    /// Virtacoinplus
    XVP,
    /// Vsync
    XVS,
    /// WhiteCoin
    XWC,
    /// ZCoin
    XZC,
    /// Yacoin
    YAC,
    /// YashCoin
    YASH,
    /// YbCoin
    YBC,
    /// Yescoin
    YES,
    /// Yocoin
    YOC,
    /// Yogold
    YOG,
    /// Zilbercoin
    ZBC,
    /// ZcCoin
    ZCC,
    /// ZClassic
    ZCL,
    /// Zdash
    ZDASH,
    /// Zcash
    ZEC,
    /// Zeitcoin
    ZEIT,
    /// Zennies
    ZENI,
    /// Zero
    ZER,
    /// Zetacoin
    ZET,
    /// Zcashshare
    ZHS,
    /// Zonecoin
    ZNE,
    /// Bitzeny
    ZNY,
    /// Zoin
    ZOI,
    /// ZSEcoin
    ZSE,
    /// Zurcoin
    ZUR,
    /// Zayedcoin
    ZYD,
}

impl FromStr for Symbol {
    type Err = String;

    fn from_str(s: &str) -> Result<Symbol, Self::Err> {
        match s {
            "EUR" => Ok(Symbol::EUR),
            "USD" => Ok(Symbol::USD),
            "ABN" => Ok(Symbol::ABN),
            "ABY" => Ok(Symbol::ABY),
            "AC" => Ok(Symbol::AC),
            "ACCI" => Ok(Symbol::ACCI),
            "ACES" => Ok(Symbol::ACES),
            "ACN" => Ok(Symbol::ACN),
            "ACOIN" => Ok(Symbol::ACOIN),
            "ACP" => Ok(Symbol::ACP),
            "ADC" => Ok(Symbol::ADC),
            "ADCN" => Ok(Symbol::ADCN),
            "ADT" => Ok(Symbol::ADT),
            "ADZ" => Ok(Symbol::ADZ),
            "AEON" => Ok(Symbol::AEON),
            "AGLC" => Ok(Symbol::AGLC),
            "AGRS" => Ok(Symbol::AGRS),
            "AIB" => Ok(Symbol::AIB),
            "AIR" => Ok(Symbol::AIR),
            "ALL" => Ok(Symbol::ALL),
            "ALTC" => Ok(Symbol::ALTC),
            "AMBER" => Ok(Symbol::AMBER),
            "AMIS" => Ok(Symbol::AMIS),
            "AMP" => Ok(Symbol::AMP),
            "AMS" => Ok(Symbol::AMS),
            "ANC" => Ok(Symbol::ANC),
            "ANS" => Ok(Symbol::ANS),
            "ANTI" => Ok(Symbol::ANTI),
            "APC" => Ok(Symbol::APC),
            "ARB" => Ok(Symbol::ARB),
            "ARCO" => Ok(Symbol::ARCO),
            "ARDR" => Ok(Symbol::ARDR),
            "ARG" => Ok(Symbol::ARG),
            "ARGUS" => Ok(Symbol::ARGUS),
            "ARI" => Ok(Symbol::ARI),
            "ARK" => Ok(Symbol::ARK),
            "ASAFE" => Ok(Symbol::ASAFE),
            "ASC" => Ok(Symbol::ASC),
            "ATMS" => Ok(Symbol::ATMS),
            "ATOM" => Ok(Symbol::ATOM),
            "ATX" => Ok(Symbol::ATX),
            "AU" => Ok(Symbol::AU),
            "AUM" => Ok(Symbol::AUM),
            "AUR" => Ok(Symbol::AUR),
            "AV" => Ok(Symbol::AV),
            "AXF" => Ok(Symbol::AXF),
            "B3" => Ok(Symbol::B3),
            "BAC" => Ok(Symbol::BAC),
            "BASH" => Ok(Symbol::BASH),
            "BAY" => Ok(Symbol::BAY),
            "BCC" => Ok(Symbol::BCC),
            "BCF" => Ok(Symbol::BCF),
            "BCN" => Ok(Symbol::BCN),
            "BCY" => Ok(Symbol::BCY),
            "BELA" => Ok(Symbol::BELA),
            "BENJI" => Ok(Symbol::BENJI),
            "BERN" => Ok(Symbol::BERN),
            "BEST" => Ok(Symbol::BEST),
            "BGC" => Ok(Symbol::BGC),
            "BIC" => Ok(Symbol::BIC),
            "BIGUP" => Ok(Symbol::BIGUP),
            "BIOB" => Ok(Symbol::BIOB),
            "BIOS" => Ok(Symbol::BIOS),
            "BIP" => Ok(Symbol::BIP),
            "BIT" => Ok(Symbol::BIT),
            "BITB" => Ok(Symbol::BITB),
            "BITBTC" => Ok(Symbol::BITBTC),
            "BITCNY" => Ok(Symbol::BITCNY),
            "BITEUR" => Ok(Symbol::BITEUR),
            "BITGOLD" => Ok(Symbol::BITGOLD),
            "BITS" => Ok(Symbol::BITS),
            "BITSILVER" => Ok(Symbol::BITSILVER),
            "BITUSD" => Ok(Symbol::BITUSD),
            "BITZ" => Ok(Symbol::BITZ),
            "BLAZR" => Ok(Symbol::BLAZR),
            "BLC" => Ok(Symbol::BLC),
            "BLITZ" => Ok(Symbol::BLITZ),
            "BLK" => Ok(Symbol::BLK),
            "BLOCK" => Ok(Symbol::BLOCK),
            "BLOCKPAY" => Ok(Symbol::BLOCKPAY),
            "BLRY" => Ok(Symbol::BLRY),
            "BLU" => Ok(Symbol::BLU),
            "BLZ" => Ok(Symbol::BLZ),
            "BOAT" => Ok(Symbol::BOAT),
            "BOB" => Ok(Symbol::BOB),
            "BOLI" => Ok(Symbol::BOLI),
            "BOND" => Ok(Symbol::BOND),
            "BOST" => Ok(Symbol::BOST),
            "BPC" => Ok(Symbol::BPC),
            "BRAIN" => Ok(Symbol::BRAIN),
            "BRIT" => Ok(Symbol::BRIT),
            "BRK" => Ok(Symbol::BRK),
            "BRX" => Ok(Symbol::BRX),
            "BSC" => Ok(Symbol::BSC),
            "BSD" => Ok(Symbol::BSD),
            "BSTAR" => Ok(Symbol::BSTAR),
            "BSTY" => Ok(Symbol::BSTY),
            "BTA" => Ok(Symbol::BTA),
            "BTB" => Ok(Symbol::BTB),
            "BTC" => Ok(Symbol::BTC),
            "BTCD" => Ok(Symbol::BTCD),
            "BTCR" => Ok(Symbol::BTCR),
            "BTCS" => Ok(Symbol::BTCS),
            "BTD" => Ok(Symbol::BTD),
            "BTG" => Ok(Symbol::BTG),
            "BTM" => Ok(Symbol::BTM),
            "BTQ" => Ok(Symbol::BTQ),
            "BTS" => Ok(Symbol::BTS),
            "BTSR" => Ok(Symbol::BTSR),
            "BTU" => Ok(Symbol::BTU),
            "BUCKS" => Ok(Symbol::BUCKS),
            "BUK" => Ok(Symbol::BUK),
            "BUMBA" => Ok(Symbol::BUMBA),
            "BUN" => Ok(Symbol::BUN),
            "BURN" => Ok(Symbol::BURN),
            "BURST" => Ok(Symbol::BURST),
            "BVC" => Ok(Symbol::BVC),
            "BXC" => Ok(Symbol::BXC),
            "BXT" => Ok(Symbol::BXT),
            "BYC" => Ok(Symbol::BYC),
            "C2" => Ok(Symbol::C2),
            "CAB" => Ok(Symbol::CAB),
            "CADASTRAL" => Ok(Symbol::CADASTRAL),
            "CAGE" => Ok(Symbol::CAGE),
            "CALC" => Ok(Symbol::CALC),
            "CANN" => Ok(Symbol::CANN),
            "CAP" => Ok(Symbol::CAP),
            "CARBON" => Ok(Symbol::CARBON),
            "CASH" => Ok(Symbol::CASH),
            "CASINO" => Ok(Symbol::CASINO),
            "CBD" => Ok(Symbol::CBD),
            "CBX" => Ok(Symbol::CBX),
            "CC" => Ok(Symbol::CC),
            "CCM100" => Ok(Symbol::CCM100),
            "CCN" => Ok(Symbol::CCN),
            "CCRB" => Ok(Symbol::CCRB),
            "CDN" => Ok(Symbol::CDN),
            "CESC" => Ok(Symbol::CESC),
            "CF" => Ok(Symbol::CF),
            "CHAO" => Ok(Symbol::CHAO),
            "CHC" => Ok(Symbol::CHC),
            "CHESS" => Ok(Symbol::CHESS),
            "CHOOF" => Ok(Symbol::CHOOF),
            "CJ" => Ok(Symbol::CJ),
            "CLAM" => Ok(Symbol::CLAM),
            "CLINT" => Ok(Symbol::CLINT),
            "CLOAK" => Ok(Symbol::CLOAK),
            "CLUB" => Ok(Symbol::CLUB),
            "CME" => Ok(Symbol::CME),
            "CMT" => Ok(Symbol::CMT),
            "CNC" => Ok(Symbol::CNC),
            "CNO" => Ok(Symbol::CNO),
            "CNT" => Ok(Symbol::CNT),
            "CON" => Ok(Symbol::CON),
            "CONX" => Ok(Symbol::CONX),
            "CORG" => Ok(Symbol::CORG),
            "COVAL" => Ok(Symbol::COVAL),
            "COXST" => Ok(Symbol::COXST),
            "CPC" => Ok(Symbol::CPC),
            "CRBIT" => Ok(Symbol::CRBIT),
            "CREVA" => Ok(Symbol::CREVA),
            "CRT" => Ok(Symbol::CRT),
            "CRW" => Ok(Symbol::CRW),
            "CRX" => Ok(Symbol::CRX),
            "CSC" => Ok(Symbol::CSC),
            "CSH" => Ok(Symbol::CSH),
            "CTO" => Ok(Symbol::CTO),
            "CUBE" => Ok(Symbol::CUBE),
            "CURE" => Ok(Symbol::CURE),
            "CV2" => Ok(Symbol::CV2),
            "CWXT" => Ok(Symbol::CWXT),
            "CXT" => Ok(Symbol::CXT),
            "CYC" => Ok(Symbol::CYC),
            "CYP" => Ok(Symbol::CYP),
            "DAR" => Ok(Symbol::DAR),
            "DASH" => Ok(Symbol::DASH),
            "DBG" => Ok(Symbol::DBG),
            "DBIC" => Ok(Symbol::DBIC),
            "DBIX" => Ok(Symbol::DBIX),
            "DBTC" => Ok(Symbol::DBTC),
            "DCR" => Ok(Symbol::DCR),
            "DCRE" => Ok(Symbol::DCRE),
            "DCT" => Ok(Symbol::DCT),
            "DEM" => Ok(Symbol::DEM),
            "DES" => Ok(Symbol::DES),
            "DEUS" => Ok(Symbol::DEUS),
            "DEX" => Ok(Symbol::DEX),
            "DGB" => Ok(Symbol::DGB),
            "DGC" => Ok(Symbol::DGC),
            "DGCS" => Ok(Symbol::DGCS),
            "DGD" => Ok(Symbol::DGD),
            "DIBC" => Ok(Symbol::DIBC),
            "DIME" => Ok(Symbol::DIME),
            "DISK" => Ok(Symbol::DISK),
            "DIX" => Ok(Symbol::DIX),
            "DLC" => Ok(Symbol::DLC),
            "DLISK" => Ok(Symbol::DLISK),
            "DMC" => Ok(Symbol::DMC),
            "DMD" => Ok(Symbol::DMD),
            "DOGE" => Ok(Symbol::DOGE),
            "DOLLAR" => Ok(Symbol::DOLLAR),
            "DOPE" => Ok(Symbol::DOPE),
            "DOT" => Ok(Symbol::DOT),
            "DP" => Ok(Symbol::DP),
            "DPAY" => Ok(Symbol::DPAY),
            "DRACO" => Ok(Symbol::DRACO),
            "DRAGON" => Ok(Symbol::DRAGON),
            "DRM" => Ok(Symbol::DRM),
            "DRS" => Ok(Symbol::DRS),
            "DSH" => Ok(Symbol::DSH),
            "DTB" => Ok(Symbol::DTB),
            "DTF" => Ok(Symbol::DTF),
            "DUB" => Ok(Symbol::DUB),
            "DUO" => Ok(Symbol::DUO),
            "DVC" => Ok(Symbol::DVC),
            "DWC" => Ok(Symbol::DWC),
            "DYN" => Ok(Symbol::DYN),
            "EAC" => Ok(Symbol::EAC),
            "EB3" => Ok(Symbol::EB3),
            "EBT" => Ok(Symbol::EBT),
            "ECC" => Ok(Symbol::ECC),
            "ECN" => Ok(Symbol::ECN),
            "EDG" => Ok(Symbol::EDG),
            "EDR" => Ok(Symbol::EDR),
            "EDRC" => Ok(Symbol::EDRC),
            "EFL" => Ok(Symbol::EFL),
            "EGC" => Ok(Symbol::EGC),
            "EGG" => Ok(Symbol::EGG),
            "EGO" => Ok(Symbol::EGO),
            "EL" => Ok(Symbol::EL),
            "ELC" => Ok(Symbol::ELC),
            "ELE" => Ok(Symbol::ELE),
            "ELS" => Ok(Symbol::ELS),
            "EMC" => Ok(Symbol::EMC),
            "EMC2" => Ok(Symbol::EMC2),
            "EMD" => Ok(Symbol::EMD),
            "EMV" => Ok(Symbol::EMV),
            "ENRG" => Ok(Symbol::ENRG),
            "ENT" => Ok(Symbol::ENT),
            "ERC" => Ok(Symbol::ERC),
            "ERY" => Ok(Symbol::ERY),
            "ESP" => Ok(Symbol::ESP),
            "ETC" => Ok(Symbol::ETC),
            "ETH" => Ok(Symbol::ETH),
            "EUC" => Ok(Symbol::EUC),
            "EVIL" => Ok(Symbol::EVIL),
            "EVO" => Ok(Symbol::EVO),
            "EXCL" => Ok(Symbol::EXCL),
            "EXP" => Ok(Symbol::EXP),
            "FAIR" => Ok(Symbol::FAIR),
            "FAZZ" => Ok(Symbol::FAZZ),
            "FC2" => Ok(Symbol::FC2),
            "FCN" => Ok(Symbol::FCN),
            "FCT" => Ok(Symbol::FCT),
            "FDC" => Ok(Symbol::FDC),
            "FEDS" => Ok(Symbol::FEDS),
            "FFC" => Ok(Symbol::FFC),
            "FIRE" => Ok(Symbol::FIRE),
            "FJC" => Ok(Symbol::FJC),
            "FLAX" => Ok(Symbol::FLAX),
            "FLDC" => Ok(Symbol::FLDC),
            "FLO" => Ok(Symbol::FLO),
            "FLT" => Ok(Symbol::FLT),
            "FLVR" => Ok(Symbol::FLVR),
            "FLY" => Ok(Symbol::FLY),
            "FRC" => Ok(Symbol::FRC),
            "FRGC" => Ok(Symbol::FRGC),
            "FRK" => Ok(Symbol::FRK),
            "FRN" => Ok(Symbol::FRN),
            "FRST" => Ok(Symbol::FRST),
            "FRWC" => Ok(Symbol::FRWC),
            "FST" => Ok(Symbol::FST),
            "FTC" => Ok(Symbol::FTC),
            "FUN" => Ok(Symbol::FUN),
            "FUND" => Ok(Symbol::FUND),
            "FUNK" => Ok(Symbol::FUNK),
            "FUZZ" => Ok(Symbol::FUZZ),
            "G3N" => Ok(Symbol::G3N),
            "GAIA" => Ok(Symbol::GAIA),
            "GAIN" => Ok(Symbol::GAIN),
            "GAM" => Ok(Symbol::GAM),
            "GAME" => Ok(Symbol::GAME),
            "GAP" => Ok(Symbol::GAP),
            "GARY" => Ok(Symbol::GARY),
            "GAY" => Ok(Symbol::GAY),
            "GB" => Ok(Symbol::GB),
            "GBC" => Ok(Symbol::GBC),
            "GBG" => Ok(Symbol::GBG),
            "GBRC" => Ok(Symbol::GBRC),
            "GBT" => Ok(Symbol::GBT),
            "GBYTE" => Ok(Symbol::GBYTE),
            "GCN" => Ok(Symbol::GCN),
            "GCR" => Ok(Symbol::GCR),
            "GEERT" => Ok(Symbol::GEERT),
            "GEMZ" => Ok(Symbol::GEMZ),
            "GEO" => Ok(Symbol::GEO),
            "GLC" => Ok(Symbol::GLC),
            "GLD" => Ok(Symbol::GLD),
            "GMB" => Ok(Symbol::GMB),
            "GML" => Ok(Symbol::GML),
            "GMX" => Ok(Symbol::GMX),
            "GNT" => Ok(Symbol::GNT),
            "GOLOS" => Ok(Symbol::GOLOS),
            "GP" => Ok(Symbol::GP),
            "GPU" => Ok(Symbol::GPU),
            "GRC" => Ok(Symbol::GRC),
            "GREV2" => Ok(Symbol::GREV2),
            "GRN" => Ok(Symbol::GRN),
            "GRS" => Ok(Symbol::GRS),
            "GRT" => Ok(Symbol::GRT),
            "GUA" => Ok(Symbol::GUA),
            "GUN" => Ok(Symbol::GUN),
            "GUP" => Ok(Symbol::GUP),
            "HAM" => Ok(Symbol::HAM),
            "HBN" => Ok(Symbol::HBN),
            "HCC" => Ok(Symbol::HCC),
            "HEAT" => Ok(Symbol::HEAT),
            "HILL" => Ok(Symbol::HILL),
            "HIRO" => Ok(Symbol::HIRO),
            "HKG" => Ok(Symbol::HKG),
            "HLB" => Ok(Symbol::HLB),
            "HMC" => Ok(Symbol::HMC),
            "HMP" => Ok(Symbol::HMP),
            "HNC" => Ok(Symbol::HNC),
            "HODL" => Ok(Symbol::HODL),
            "HONEY" => Ok(Symbol::HONEY),
            "HPC" => Ok(Symbol::HPC),
            "HTC" => Ok(Symbol::HTC),
            "HTML5" => Ok(Symbol::HTML5),
            "HUC" => Ok(Symbol::HUC),
            "HVCO" => Ok(Symbol::HVCO),
            "HXX" => Ok(Symbol::HXX),
            "HYP" => Ok(Symbol::HYP),
            "HZ" => Ok(Symbol::HZ),
            "I0C" => Ok(Symbol::I0C),
            "IBANK" => Ok(Symbol::IBANK),
            "ICASH" => Ok(Symbol::ICASH),
            "ICN" => Ok(Symbol::ICN),
            "ICOB" => Ok(Symbol::ICOB),
            "ICON" => Ok(Symbol::ICON),
            "ICOO" => Ok(Symbol::ICOO),
            "IFC" => Ok(Symbol::IFC),
            "IFLT" => Ok(Symbol::IFLT),
            "IMPCH" => Ok(Symbol::IMPCH),
            "IMPS" => Ok(Symbol::IMPS),
            "IMS" => Ok(Symbol::IMS),
            "IMX" => Ok(Symbol::IMX),
            "INCNT" => Ok(Symbol::INCNT),
            "INFX" => Ok(Symbol::INFX),
            "INPAY" => Ok(Symbol::INPAY),
            "INSANE" => Ok(Symbol::INSANE),
            "IOC" => Ok(Symbol::IOC),
            "ION" => Ok(Symbol::ION),
            "IOP" => Ok(Symbol::IOP),
            "ISL" => Ok(Symbol::ISL),
            "IVZ" => Ok(Symbol::IVZ),
            "IXC" => Ok(Symbol::IXC),
            "J" => Ok(Symbol::J),
            "JIN" => Ok(Symbol::JIN),
            "JINN" => Ok(Symbol::JINN),
            "JIO" => Ok(Symbol::JIO),
            "JNS" => Ok(Symbol::JNS),
            "JOBS" => Ok(Symbol::JOBS),
            "JWL" => Ok(Symbol::JWL),
            "KASHH" => Ok(Symbol::KASHH),
            "KED" => Ok(Symbol::KED),
            "KLC" => Ok(Symbol::KLC),
            "KMD" => Ok(Symbol::KMD),
            "KOBO" => Ok(Symbol::KOBO),
            "KORE" => Ok(Symbol::KORE),
            "KRB" => Ok(Symbol::KRB),
            "KTN" => Ok(Symbol::KTN),
            "KURT" => Ok(Symbol::KURT),
            "KUSH" => Ok(Symbol::KUSH),
            "LANA" => Ok(Symbol::LANA),
            "LAZ" => Ok(Symbol::LAZ),
            "LBC" => Ok(Symbol::LBC),
            "LDCN" => Ok(Symbol::LDCN),
            "LDOGE" => Ok(Symbol::LDOGE),
            "LEA" => Ok(Symbol::LEA),
            "LEC" => Ok(Symbol::LEC),
            "LEO" => Ok(Symbol::LEO),
            "LEPEN" => Ok(Symbol::LEPEN),
            "LEX" => Ok(Symbol::LEX),
            "LFC" => Ok(Symbol::LFC),
            "LIR" => Ok(Symbol::LIR),
            "LKC" => Ok(Symbol::LKC),
            "LKK" => Ok(Symbol::LKK),
            "LMC" => Ok(Symbol::LMC),
            "LOG" => Ok(Symbol::LOG),
            "LOT" => Ok(Symbol::LOT),
            "LSK" => Ok(Symbol::LSK),
            "LTB" => Ok(Symbol::LTB),
            "LTBC" => Ok(Symbol::LTBC),
            "LTC" => Ok(Symbol::LTC),
            "LTCR" => Ok(Symbol::LTCR),
            "LTH" => Ok(Symbol::LTH),
            "LUNA" => Ok(Symbol::LUNA),
            "LVPS" => Ok(Symbol::LVPS),
            "MAC" => Ok(Symbol::MAC),
            "MAD" => Ok(Symbol::MAD),
            "MAID" => Ok(Symbol::MAID),
            "MAR" => Ok(Symbol::MAR),
            "MARX" => Ok(Symbol::MARX),
            "MAVRO" => Ok(Symbol::MAVRO),
            "MAX" => Ok(Symbol::MAX),
            "MBIT" => Ok(Symbol::MBIT),
            "MBL" => Ok(Symbol::MBL),
            "MEC" => Ok(Symbol::MEC),
            "MED" => Ok(Symbol::MED),
            "MEME" => Ok(Symbol::MEME),
            "MEOW" => Ok(Symbol::MEOW),
            "MER" => Ok(Symbol::MER),
            "METAL" => Ok(Symbol::METAL),
            "MG" => Ok(Symbol::MG),
            "MGM" => Ok(Symbol::MGM),
            "MI" => Ok(Symbol::MI),
            "MILO" => Ok(Symbol::MILO),
            "MINT" => Ok(Symbol::MINT),
            "MLN" => Ok(Symbol::MLN),
            "MMXVI" => Ok(Symbol::MMXVI),
            "MND" => Ok(Symbol::MND),
            "MNM" => Ok(Symbol::MNM),
            "MOIN" => Ok(Symbol::MOIN),
            "MOJO" => Ok(Symbol::MOJO),
            "MONA" => Ok(Symbol::MONA),
            "MONETA" => Ok(Symbol::MONETA),
            "MONEY" => Ok(Symbol::MONEY),
            "MOON" => Ok(Symbol::MOON),
            "MOTO" => Ok(Symbol::MOTO),
            "MSCN" => Ok(Symbol::MSCN),
            "MST" => Ok(Symbol::MST),
            "MTLMC3" => Ok(Symbol::MTLMC3),
            "MTM" => Ok(Symbol::MTM),
            "MUE" => Ok(Symbol::MUE),
            "MUG" => Ok(Symbol::MUG),
            "MUSE" => Ok(Symbol::MUSE),
            "MUSIC" => Ok(Symbol::MUSIC),
            "MXT" => Ok(Symbol::MXT),
            "MZC" => Ok(Symbol::MZC),
            "NAUT" => Ok(Symbol::NAUT),
            "NAV" => Ok(Symbol::NAV),
            "NBE" => Ok(Symbol::NBE),
            "NBIT" => Ok(Symbol::NBIT),
            "NEOS" => Ok(Symbol::NEOS),
            "NET" => Ok(Symbol::NET),
            "NETKO" => Ok(Symbol::NETKO),
            "NEU" => Ok(Symbol::NEU),
            "NEVA" => Ok(Symbol::NEVA),
            "NEWB" => Ok(Symbol::NEWB),
            "NKA" => Ok(Symbol::NKA),
            "NLC2" => Ok(Symbol::NLC2),
            "NLG" => Ok(Symbol::NLG),
            "NMC" => Ok(Symbol::NMC),
            "NOBL" => Ok(Symbol::NOBL),
            "NODC" => Ok(Symbol::NODC),
            "NOTE" => Ok(Symbol::NOTE),
            "NSR" => Ok(Symbol::NSR),
            "NTCC" => Ok(Symbol::NTCC),
            "NTRN" => Ok(Symbol::NTRN),
            "NVC" => Ok(Symbol::NVC),
            "NXC" => Ok(Symbol::NXC),
            "NXS" => Ok(Symbol::NXS),
            "NXT" => Ok(Symbol::NXT),
            "NYAN" => Ok(Symbol::NYAN),
            "NYC" => Ok(Symbol::NYC),
            "OBITS" => Ok(Symbol::OBITS),
            "OCEAN" => Ok(Symbol::OCEAN),
            "OCOW" => Ok(Symbol::OCOW),
            "OK" => Ok(Symbol::OK),
            "OMC" => Ok(Symbol::OMC),
            "OMNI" => Ok(Symbol::OMNI),
            "OP" => Ok(Symbol::OP),
            "OPAL" => Ok(Symbol::OPAL),
            "OPES" => Ok(Symbol::OPES),
            "ORB" => Ok(Symbol::ORB),
            "ORLY" => Ok(Symbol::ORLY),
            "OS76" => Ok(Symbol::OS76),
            "P7C" => Ok(Symbol::P7C),
            "PAC" => Ok(Symbol::PAC),
            "PAK" => Ok(Symbol::PAK),
            "PANGEA" => Ok(Symbol::PANGEA),
            "PASC" => Ok(Symbol::PASC),
            "PASL" => Ok(Symbol::PASL),
            "PAYP" => Ok(Symbol::PAYP),
            "PBC" => Ok(Symbol::PBC),
            "PCS" => Ok(Symbol::PCS),
            "PDC" => Ok(Symbol::PDC),
            "PDG" => Ok(Symbol::PDG),
            "PEPECASH" => Ok(Symbol::PEPECASH),
            "PEX" => Ok(Symbol::PEX),
            "PHO" => Ok(Symbol::PHO),
            "PHS" => Ok(Symbol::PHS),
            "PIE" => Ok(Symbol::PIE),
            "PIGGY" => Ok(Symbol::PIGGY),
            "PINK" => Ok(Symbol::PINK),
            "PIO" => Ok(Symbol::PIO),
            "PIP" => Ok(Symbol::PIP),
            "PIVX" => Ok(Symbol::PIVX),
            "PIZZA" => Ok(Symbol::PIZZA),
            "PKB" => Ok(Symbol::PKB),
            "PLNC" => Ok(Symbol::PLNC),
            "PLU" => Ok(Symbol::PLU),
            "PND" => Ok(Symbol::PND),
            "POKE" => Ok(Symbol::POKE),
            "PONZI" => Ok(Symbol::PONZI),
            "POP" => Ok(Symbol::POP),
            "POST" => Ok(Symbol::POST),
            "POSW" => Ok(Symbol::POSW),
            "POT" => Ok(Symbol::POT),
            "PPC" => Ok(Symbol::PPC),
            "PR" => Ok(Symbol::PR),
            "PRC" => Ok(Symbol::PRC),
            "PRES" => Ok(Symbol::PRES),
            "PRM" => Ok(Symbol::PRM),
            "PRX" => Ok(Symbol::PRX),
            "PSB" => Ok(Symbol::PSB),
            "PSY" => Ok(Symbol::PSY),
            "PTC" => Ok(Symbol::PTC),
            "PULSE" => Ok(Symbol::PULSE),
            "PUT" => Ok(Symbol::PUT),
            "PWR" => Ok(Symbol::PWR),
            "PX" => Ok(Symbol::PX),
            "PXC" => Ok(Symbol::PXC),
            "PXI" => Ok(Symbol::PXI),
            "QBC" => Ok(Symbol::QBC),
            "QBK" => Ok(Symbol::QBK),
            "QBT" => Ok(Symbol::QBT),
            "QCN" => Ok(Symbol::QCN),
            "QORA" => Ok(Symbol::QORA),
            "QRK" => Ok(Symbol::QRK),
            "QTL" => Ok(Symbol::QTL),
            "QWARK" => Ok(Symbol::QWARK),
            "RADS" => Ok(Symbol::RADS),
            "RAREPEPEPRTY" => Ok(Symbol::RAREPEPEPRTY),
            "RBIES" => Ok(Symbol::RBIES),
            "RBT" => Ok(Symbol::RBT),
            "RBX" => Ok(Symbol::RBX),
            "RBY" => Ok(Symbol::RBY),
            "RC" => Ok(Symbol::RC),
            "RCN" => Ok(Symbol::RCN),
            "RDD" => Ok(Symbol::RDD),
            "RED" => Ok(Symbol::RED),
            "REE" => Ok(Symbol::REE),
            "REP" => Ok(Symbol::REP),
            "REV" => Ok(Symbol::REV),
            "RHFC" => Ok(Symbol::RHFC),
            "RIC" => Ok(Symbol::RIC),
            "RICHX" => Ok(Symbol::RICHX),
            "RIDE" => Ok(Symbol::RIDE),
            "RISE" => Ok(Symbol::RISE),
            "RLC" => Ok(Symbol::RLC),
            "RNS" => Ok(Symbol::RNS),
            "ROUND" => Ok(Symbol::ROUND),
            "ROYAL" => Ok(Symbol::ROYAL),
            "RPC" => Ok(Symbol::RPC),
            "RUBIT" => Ok(Symbol::RUBIT),
            "RYCN" => Ok(Symbol::RYCN),
            "SAFEX" => Ok(Symbol::SAFEX),
            "SAK" => Ok(Symbol::SAK),
            "SANDG" => Ok(Symbol::SANDG),
            "SATOSHICARD" => Ok(Symbol::SATOSHICARD),
            "SBD" => Ok(Symbol::SBD),
            "SC" => Ok(Symbol::SC),
            "SCORE" => Ok(Symbol::SCORE),
            "SCOT" => Ok(Symbol::SCOT),
            "SCRT" => Ok(Symbol::SCRT),
            "SDC" => Ok(Symbol::SDC),
            "SDP" => Ok(Symbol::SDP),
            "SEQ" => Ok(Symbol::SEQ),
            "SFC" => Ok(Symbol::SFC),
            "SH" => Ok(Symbol::SH),
            "SHELL" => Ok(Symbol::SHELL),
            "SHIFT" => Ok(Symbol::SHIFT),
            "SHORTY" => Ok(Symbol::SHORTY),
            "SIB" => Ok(Symbol::SIB),
            "SJCX" => Ok(Symbol::SJCX),
            "SKC" => Ok(Symbol::SKC),
            "SKR" => Ok(Symbol::SKR),
            "SKY" => Ok(Symbol::SKY),
            "SLFI" => Ok(Symbol::SLFI),
            "SLG" => Ok(Symbol::SLG),
            "SLING" => Ok(Symbol::SLING),
            "SLR" => Ok(Symbol::SLR),
            "SLS" => Ok(Symbol::SLS),
            "SMC" => Ok(Symbol::SMC),
            "SMLY" => Ok(Symbol::SMLY),
            "SNGLS" => Ok(Symbol::SNGLS),
            "SNRG" => Ok(Symbol::SNRG),
            "SOAR" => Ok(Symbol::SOAR),
            "SONG" => Ok(Symbol::SONG),
            "SOON" => Ok(Symbol::SOON),
            "SOUL" => Ok(Symbol::SOUL),
            "SPACE" => Ok(Symbol::SPACE),
            "SPEX" => Ok(Symbol::SPEX),
            "SPHR" => Ok(Symbol::SPHR),
            "SPORT" => Ok(Symbol::SPORT),
            "SPR" => Ok(Symbol::SPR),
            "SPRTS" => Ok(Symbol::SPRTS),
            "SPT" => Ok(Symbol::SPT),
            "SRC" => Ok(Symbol::SRC),
            "START" => Ok(Symbol::START),
            "STEEM" => Ok(Symbol::STEEM),
            "STEPS" => Ok(Symbol::STEPS),
            "STRAT" => Ok(Symbol::STRAT),
            "STRB" => Ok(Symbol::STRB),
            "STS" => Ok(Symbol::STS),
            "STV" => Ok(Symbol::STV),
            "SWIFT" => Ok(Symbol::SWIFT),
            "SWING" => Ok(Symbol::SWING),
            "SWT" => Ok(Symbol::SWT),
            "SXC" => Ok(Symbol::SXC),
            "SYNX" => Ok(Symbol::SYNX),
            "SYS" => Ok(Symbol::SYS),
            "TAAS" => Ok(Symbol::TAAS),
            "TAG" => Ok(Symbol::TAG),
            "TAGR" => Ok(Symbol::TAGR),
            "TAJ" => Ok(Symbol::TAJ),
            "TALK" => Ok(Symbol::TALK),
            "TATO" => Ok(Symbol::TATO),
            "TCOIN" => Ok(Symbol::TCOIN),
            "TCR" => Ok(Symbol::TCR),
            "TEAM" => Ok(Symbol::TEAM),
            "TEK" => Ok(Symbol::TEK),
            "TELL" => Ok(Symbol::TELL),
            "TERA" => Ok(Symbol::TERA),
            "TES" => Ok(Symbol::TES),
            "TESLA" => Ok(Symbol::TESLA),
            "TGC" => Ok(Symbol::TGC),
            "THC" => Ok(Symbol::THC),
            "THS" => Ok(Symbol::THS),
            "TIC" => Ok(Symbol::TIC),
            "TIME" => Ok(Symbol::TIME),
            "TIPS" => Ok(Symbol::TIPS),
            "TIT" => Ok(Symbol::TIT),
            "TIX" => Ok(Symbol::TIX),
            "TKS" => Ok(Symbol::TKS),
            "TODAY" => Ok(Symbol::TODAY),
            "TOKEN" => Ok(Symbol::TOKEN),
            "TOR" => Ok(Symbol::TOR),
            "TP1" => Ok(Symbol::TP1),
            "TRC" => Ok(Symbol::TRC),
            "TRI" => Ok(Symbol::TRI),
            "TRICK" => Ok(Symbol::TRICK),
            "TRIG" => Ok(Symbol::TRIG),
            "TRK" => Ok(Symbol::TRK),
            "TROLL" => Ok(Symbol::TROLL),
            "TROPTIONS" => Ok(Symbol::TROPTIONS),
            "TRST" => Ok(Symbol::TRST),
            "TRUMP" => Ok(Symbol::TRUMP),
            "TRUST" => Ok(Symbol::TRUST),
            "TSTR" => Ok(Symbol::TSTR),
            "TTC" => Ok(Symbol::TTC),
            "TX" => Ok(Symbol::TX),
            "U" => Ok(Symbol::U),
            "UBQ" => Ok(Symbol::UBQ),
            "UFO" => Ok(Symbol::UFO),
            "UIS" => Ok(Symbol::UIS),
            "UNB" => Ok(Symbol::UNB),
            "UNC" => Ok(Symbol::UNC),
            "UNI" => Ok(Symbol::UNI),
            "UNIBURST" => Ok(Symbol::UNIBURST),
            "UNIC" => Ok(Symbol::UNIC),
            "UNIT" => Ok(Symbol::UNIT),
            "UNITS" => Ok(Symbol::UNITS),
            "UNITY" => Ok(Symbol::UNITY),
            "UNO" => Ok(Symbol::UNO),
            "UR" => Ok(Symbol::UR),
            "URC" => Ok(Symbol::URC),
            "URO" => Ok(Symbol::URO),
            "USC" => Ok(Symbol::USC),
            "USDT" => Ok(Symbol::USDT),
            "USNBT" => Ok(Symbol::USNBT),
            "UTA" => Ok(Symbol::UTA),
            "UTC" => Ok(Symbol::UTC),
            "VAL" => Ok(Symbol::VAL),
            "VASH" => Ok(Symbol::VASH),
            "VC" => Ok(Symbol::VC),
            "VEC2" => Ok(Symbol::VEC2),
            "VGC" => Ok(Symbol::VGC),
            "VIA" => Ok(Symbol::VIA),
            "VIDZ" => Ok(Symbol::VIDZ),
            "VIP" => Ok(Symbol::VIP),
            "VISIO" => Ok(Symbol::VISIO),
            "VLT" => Ok(Symbol::VLT),
            "VLTC" => Ok(Symbol::VLTC),
            "VOX" => Ok(Symbol::VOX),
            "VPRC" => Ok(Symbol::VPRC),
            "VRC" => Ok(Symbol::VRC),
            "VRM" => Ok(Symbol::VRM),
            "VRS" => Ok(Symbol::VRS),
            "VSL" => Ok(Symbol::VSL),
            "VTA" => Ok(Symbol::VTA),
            "VTC" => Ok(Symbol::VTC),
            "VTR" => Ok(Symbol::VTR),
            "VTY" => Ok(Symbol::VTY),
            "WA" => Ok(Symbol::WA),
            "WARP" => Ok(Symbol::WARP),
            "WAVES" => Ok(Symbol::WAVES),
            "WAY" => Ok(Symbol::WAY),
            "WBB" => Ok(Symbol::WBB),
            "WCT" => Ok(Symbol::WCT),
            "WDC" => Ok(Symbol::WDC),
            "WEC" => Ok(Symbol::WEC),
            "WEX" => Ok(Symbol::WEX),
            "WGC" => Ok(Symbol::WGC),
            "WINGS" => Ok(Symbol::WINGS),
            "WMC" => Ok(Symbol::WMC),
            "WORM" => Ok(Symbol::WORM),
            "WOW" => Ok(Symbol::WOW),
            "WSX" => Ok(Symbol::WSX),
            "WYV" => Ok(Symbol::WYV),
            "X2" => Ok(Symbol::X2),
            "XAS" => Ok(Symbol::XAS),
            "XAU" => Ok(Symbol::XAU),
            "XAUR" => Ok(Symbol::XAUR),
            "XBB" => Ok(Symbol::XBB),
            "XBC" => Ok(Symbol::XBC),
            "XBTC21" => Ok(Symbol::XBTC21),
            "XBTS" => Ok(Symbol::XBTS),
            "XBY" => Ok(Symbol::XBY),
            "XCI" => Ok(Symbol::XCI),
            "XCN" => Ok(Symbol::XCN),
            "XCO" => Ok(Symbol::XCO),
            "XCP" => Ok(Symbol::XCP),
            "XCRE" => Ok(Symbol::XCRE),
            "XCT" => Ok(Symbol::XCT),
            "XDE2" => Ok(Symbol::XDE2),
            "XDN" => Ok(Symbol::XDN),
            "XEM" => Ok(Symbol::XEM),
            "XEN" => Ok(Symbol::XEN),
            "XFC" => Ok(Symbol::XFC),
            "XGR" => Ok(Symbol::XGR),
            "XHI" => Ok(Symbol::XHI),
            "XID" => Ok(Symbol::XID),
            "XJO" => Ok(Symbol::XJO),
            "XLM" => Ok(Symbol::XLM),
            "XLR" => Ok(Symbol::XLR),
            "XMG" => Ok(Symbol::XMG),
            "XMR" => Ok(Symbol::XMR),
            "XMY" => Ok(Symbol::XMY),
            "XNG" => Ok(Symbol::XNG),
            "XOC" => Ok(Symbol::XOC),
            "XOT" => Ok(Symbol::XOT),
            "XP" => Ok(Symbol::XP),
            "XPD" => Ok(Symbol::XPD),
            "XPM" => Ok(Symbol::XPM),
            "XPTX" => Ok(Symbol::XPTX),
            "XPY" => Ok(Symbol::XPY),
            "XQN" => Ok(Symbol::XQN),
            "XRA" => Ok(Symbol::XRA),
            "XRB" => Ok(Symbol::XRB),
            "XRC" => Ok(Symbol::XRC),
            "XRE" => Ok(Symbol::XRE),
            "XRP" => Ok(Symbol::XRP),
            "XSPEC" => Ok(Symbol::XSPEC),
            "XST" => Ok(Symbol::XST),
            "XSTC" => Ok(Symbol::XSTC),
            "XTC" => Ok(Symbol::XTC),
            "XTO" => Ok(Symbol::XTO),
            "XVC" => Ok(Symbol::XVC),
            "XVE" => Ok(Symbol::XVE),
            "XVG" => Ok(Symbol::XVG),
            "XVP" => Ok(Symbol::XVP),
            "XVS" => Ok(Symbol::XVS),
            "XWC" => Ok(Symbol::XWC),
            "XZC" => Ok(Symbol::XZC),
            "YAC" => Ok(Symbol::YAC),
            "YASH" => Ok(Symbol::YASH),
            "YBC" => Ok(Symbol::YBC),
            "YES" => Ok(Symbol::YES),
            "YOC" => Ok(Symbol::YOC),
            "YOG" => Ok(Symbol::YOG),
            "ZBC" => Ok(Symbol::ZBC),
            "ZCC" => Ok(Symbol::ZCC),
            "ZCL" => Ok(Symbol::ZCL),
            "ZDASH" => Ok(Symbol::ZDASH),
            "ZEC" => Ok(Symbol::ZEC),
            "ZEIT" => Ok(Symbol::ZEIT),
            "ZENI" => Ok(Symbol::ZENI),
            "ZER" => Ok(Symbol::ZER),
            "ZET" => Ok(Symbol::ZET),
            "ZHS" => Ok(Symbol::ZHS),
            "ZNE" => Ok(Symbol::ZNE),
            "ZNY" => Ok(Symbol::ZNY),
            "ZOI" => Ok(Symbol::ZOI),
            "ZSE" => Ok(Symbol::ZSE),
            "ZUR" => Ok(Symbol::ZUR),
            "ZYD" => Ok(Symbol::ZYD),
            _ => Err(format!("invalid currency symbol: {}", s)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_str() {
        assert_eq!(Symbol::from_str("BTC").unwrap(), Symbol::BTC);
        assert_eq!(Symbol::from_str("USD").unwrap(), Symbol::USD);
    }
}
